feat: add uniswap ui
elimu-ai/web3-liquidity-rewards-ui pull request #21
Opened 2022-08-04 08:02 UTC by Bender-22

https://app.dework.xyz/elimuai/web3-integration?taskId=b7a6bd83-27c9-44b0-a2fb-ded788ec6e81

2022-08-05 04:40 UTC, nya-elimuai commented on abis/UniswapPoolRewards.json
> +{
Is this mainnet or Rinkeby?

2022-08-05 04:41 UTC, nya-elimuai commented on pages/uniswap.tsx
> +import UniswapPoolRewards from '../abis/UniswapPoolRewards.json'
We need to change the way ABIs are loaded when moving from Rinkeby to Mainnet.

2022-08-05 04:42 UTC, nya-elimuai commented on pages/uniswap.tsx
> +    args: ['0xb8b6430b58a4fbc57bd5cd7715d318065f2dcd81', ethers.utils.parseUnits('1000')]
Replace hardcoded values with variables.

2022-08-05 04:42 UTC, nya-elimuai commented on pages/uniswap.tsx
> +    contractInterface: UniswapPoolRewards.abi,
Replace hardcoded values with variables.

2022-08-05 04:43 UTC, nya-elimuai commented on pages/uniswap.tsx
> +                <DepositButtonWrapper depositAmount={0.1} />
Replace hardcoded amount with variable.

2022-08-05 04:43 UTC, nya-elimuai requested changes
Requested to replace hardcoded values.

2022-08-05 05:03 UTC, jo-elimu requested changes
Instead of using 1,000, can we fetch the account's amount of pool tokens, and then ask for the approval of that specific amount?

2023-06-22 09:16 UTC, jo-elimu requested changes
I'm getting a `ContractFunctionExecutionError` in the UI: https://deploy-preview-21--web3-liquidity-rewards-ui.netlify.app/uniswap

![Screenshot 2023-06-22 171432](https://github.com/elimu-ai/web3-liquidity-rewards-ui/assets/1451036/ded2a287-a919-4f2e-a083-e7890dea42d9)

2023-06-23 14:30 UTC, jo-elimu approved these changes

2023-06-23 14:37 UTC, nya-elimu approved these changes

2023-06-23 14:37 UTC, merged